[package]
name = "exastash"
version = "2.0.0"
edition = "2018"
authors = ["Ivan Kozik <ivan@ludios.org>"]

[[bin]]
name = "es"
path = "src/main.rs"

[dependencies]
# Turn off the default secure mode
mimalloc = { version = "0.1", default-features = false }
anyhow = "1.0"
thiserror = "1.0"
async-recursion = "0.3"
aes-ctr = "0.6"
crc32c = "0.5"
md-5 = "0.9"
bytes = "0.5"
byteorder = "1.3"
data-encoding = "2"
directories = "3"
custom_debug_derive = "0.5"
once_cell = "1"
num = "0.3"
regex = "1"
gethostname = "0.2"
hex = "0.4"
clap = "2"
structopt = "0.3"
rand = "0.7"
# Waiting for https://github.com/briansmith/ring/pull/909
ring = { git = "https://github.com/ludios/ring", branch = "prime" }
sqlx = { git = "https://github.com/launchbadge/sqlx", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "uuid", "chrono", "json" ] }
# Vendored openssl for sqlx
openssl = { version = "0.10", features = [ "vendored" ] }
uuid = "0.8"
chrono = "0.4"
yup-oauth2 = { git = "https://github.com/ludios/yup-oauth2", branch = "prime" }
serial_test = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde-hex = "0.1"
toml = "0.5"
tokio = { version = "0.2", features = ["macros", "rt-core", "fs", "io-util", "io-driver"] }
tokio-util = { version = "0.3", features = ["compat"] }
tracing = "0.1"
tracing-subscriber = "0.2"
hyper = "0.13"
hyper-rustls = "0.21"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "stream", "json"] }
futures = "0.3"
futures-async-stream = "0.2"
pin-project = "1.0"
parking_lot = "0.11"
polyfuse = { git = "https://github.com/ubnt-intrepid/polyfuse" }
polyfuse-tokio = { git = "https://github.com/ubnt-intrepid/polyfuse" }
libc = "0.2"
zstd = "0.5"
# Waiting for https://github.com/bcmyers/num-format/pull/20
num-format = { git = "https://github.com/ludios/num-format" }
yansi = "0.5"

[dev-dependencies]
atomic-counter = "1.0"

[patch.crates-io]
# Need a matching version for the ring in
# reqwest -> hyper-rustls -> rustls -> ring
ring = { git = "https://github.com/ludios/ring", branch = "prime" }

[profile.dev]
# Reduce debug rebuild time
# https://github.com/rust-gamedev/wg/issues/50#issuecomment-527160611
debug = false

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
