[package]
name = "terastash"
version = "0.1.0"
authors = ["Ivan Kozik <ivan@ludios.org>"]

[[bin]]
name = "ts"

[dependencies]
regex = "*"
regex_macros = "*"
num = "*"
docopt = "*"
rustc-serialize = "*"
toml = "*"
# Note: also include Cargo license in our LICENSE bundle;
# we copied some Toml handling code from Cargo

[dependencies.mysql]
mysql = "*"
default-features = false
features = ["socket"]
