[package]
name = "exastash"
version = "2.0.0"
edition = "2018"
authors = ["Ivan Kozik <ivan@ludios.org>"]

[[bin]]
name = "es"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-recursion = "0.3"
aes = "0.4"
ctr = "0.4"
crc32c = "0.4"
md-5 = "0.9"
bytes = "0.5"
byteorder = "1.3"
data-encoding = "2.2"
custom_debug_derive = "0.4"
once_cell = "1.0"
chrono = "0.4"
num = "0.3"
regex = "1.0"
gethostname = "0.2"
structopt = "0.3"
# Waiting for https://github.com/briansmith/ring/pull/909
ring = { git = "https://github.com/ludios/ring", branch = "prime" }
postgres = { version = "0.17", features = ["with-chrono-0_4", "with-serde_json-1"] }
postgres-protocol = "0.5"
postgres-types = { version = "0.1.0", features = ["derive"] }
yup-oauth2 = { git = "https://github.com/ludios/yup-oauth2", branch = "prime" }
serde = "1.0"
serde_json = "1.0"
serde-hex = "0.1"
tokio = { version = "0.2", features = ["macros", "rt-core", "fs", "io-util", "io-driver"] }
tokio-util = { version = "0.3", features = ["compat"] }
tokio-postgres = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
hyper = "0.13"
hyper-rustls = "0.20"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "stream", "json"] }
futures = "0.3"
futures-async-stream = "0.2"
pin-project = "0.4"
parking_lot = "0.10"

[dev-dependencies]
atomic-counter = "1.0"

[patch.crates-io]
# Need a matching version for the ring in
# reqwest -> hyper-rustls -> rustls -> ring
ring = { git = "https://github.com/ludios/ring", branch = "prime" }

[profile.dev]
# Reduce debug rebuild time
# https://github.com/rust-gamedev/wg/issues/50#issuecomment-527160611
debug = false

[profile.release]
overflow-checks = true
