[package]
name = "exastash"
version = "2.0.0"
edition = "2018"
authors = ["Ivan Kozik <ivan@ludios.org>"]

[[bin]]
name = "es"
path = "src/main.rs"

[dependencies]
num = "0.2.0"
structopt = "0.3.5"
postgres = { git = "https://github.com/sfackler/rust-postgres", features = ["with-chrono-0_4"] }
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres" }
anyhow = "1.0"

[profile.dev]
# Reduce debug rebuild time
# https://github.com/rust-gamedev/wg/issues/50#issuecomment-527160611
debug = false
