-- text instead of bytea, see the UTF-8 rationale on linux_basename
CREATE DOMAIN symlink_pathname AS text
    -- ext4 and btrfs limit the symlink target to ~4096 bytes.
    -- xfs limits the symlink target to 1024 bytes.
    -- We follow the lower limit in case symlinks need to be copied to XFS.
    --
    -- Linux does not allow empty pathnames: https://lwn.net/Articles/551224/
    CHECK (octet_length(VALUE) >= 1 AND octet_length(VALUE) <= 1024);

CREATE DOMAIN hostname AS text CHECK (octet_length(VALUE) >= 1 AND octet_length(VALUE) <= 253);

-- We want a table per inode type, but we must never let ino's overlap
-- between tables.  Instead of using a trigger to ensure the other tables
-- do not have the ino, just use nonoverlapping ino ranges for each type.
--
-- inode map (inclusive ranges):
-- -512 * 2^54  to               1  [forbidden]
--           2  to        2^54 - 1  dirs
--        2^54  to  170 * 2^54 - 1  [reserved]
--  170 * 2^54  to  171 * 2^54 - 1  files
--  171 * 2^54  to  341 * 2^54 - 1  [reserved]
--  341 * 2^54  to  342 * 2^54 - 1  symlinks
--  342 * 2^54  to  512 * 2^54 - 1  [reserved]

-- We don't store uid, gid, and the exact mode; those can be decided and
-- changed globally by the user.
CREATE TABLE dirs (
    -- inode 0 is not used by Linux filesystems (0 means NULL).
    -- inode 1 is used by Linux filesystems for bad blocks information.
    -- inode 2 is used for /
    -- Start with inode 3 for all other inodes.
    ino             bigint            GENERATED BY DEFAULT AS IDENTITY (START WITH 3) PRIMARY KEY CHECK (ino >= 2 AND ino <= 18014398509481983),
    mtime           timespec64        NOT NULL,

    birth_time      timespec64        NOT NULL,
    -- When/where/with what exastash version was this inode produced?
    birth_version   smallint          NOT NULL REFERENCES exastash_versions (version_id),
    birth_hostname  hostname          NOT NULL
);
REVOKE TRUNCATE ON dirs FROM current_user;

CREATE TABLE files (
    ino             bigint            GENERATED BY DEFAULT AS IDENTITY (START WITH 3062447746611937280) PRIMARY KEY CHECK (ino >= 3062447746611937280 AND ino <= 3080462145121419263),
    mtime           timespec64        NOT NULL,
    size            bigint            NOT NULL CHECK (size >= 0),
    executable      boolean           NOT NULL,

    birth_time      timespec64        NOT NULL,
    birth_version   smallint          NOT NULL REFERENCES exastash_versions (version_id),
    birth_hostname  hostname          NOT NULL
);
REVOKE TRUNCATE ON files FROM current_user;

CREATE TABLE symlinks (
    ino             bigint            GENERATED BY DEFAULT AS IDENTITY (START WITH 6142909891733356544) PRIMARY KEY CHECK (ino >= 6142909891733356544 AND ino <= 6160924290242838527),
    mtime           timespec64        NOT NULL,
    symlink_target  symlink_pathname  NOT NULL,

    birth_time      timespec64        NOT NULL,
    birth_version   smallint          NOT NULL REFERENCES exastash_versions (version_id),
    birth_hostname  hostname          NOT NULL
);
REVOKE TRUNCATE ON symlinks FROM current_user;


CREATE TRIGGER dirs_check_update
    BEFORE UPDATE ON dirs
    FOR EACH ROW
    WHEN (
        OLD.ino != NEW.ino OR
        OLD.birth_time != NEW.birth_time OR
        OLD.birth_version != NEW.birth_version OR
        OLD.birth_hostname != NEW.birth_hostname
    )
    EXECUTE FUNCTION raise_exception('cannot change ino or birth_* columns');

CREATE TRIGGER files_check_update
    BEFORE UPDATE ON files
    FOR EACH ROW
    WHEN (
        OLD.ino != NEW.ino OR
        OLD.birth_time != NEW.birth_time OR
        OLD.birth_version != NEW.birth_version OR
        OLD.birth_hostname != NEW.birth_hostname
    )
    EXECUTE FUNCTION raise_exception('cannot change ino or birth_* columns');

CREATE TRIGGER symlinks_check_update
    BEFORE UPDATE ON symlinks
    FOR EACH ROW
    WHEN (
        OLD.ino != NEW.ino OR
        OLD.symlink_target != NEW.symlink_target OR
        OLD.birth_time != NEW.birth_time OR
        OLD.birth_version != NEW.birth_version OR
        OLD.birth_hostname != NEW.birth_hostname
    )
    EXECUTE FUNCTION raise_exception('cannot change ino, symlink_target, or birth_* columns');
